const sampleListings = [
  {
    title: "Goyal Stationery",
    name: "Goyal Stationery",
    category: "stationery",
    location: "Sector 10, Noida",
    description: "Best place to buy stationery items at low price.",
    rating: 4.3,
    openHours: "9 AM - 8 PM",
    contact: "9876543210",
    image: "https://source.unsplash.com/300x200/?stationery,shop",
    verified: true,
    tags: ["notebooks", "pens", "xerox"]
  },
  {
    title: "Sharma Book Depot",
    name: "Sharma Book Depot",
    category: "stationery",
    location: "Rajpur Road, Dehradun",
    description: "All school & college books available.",
    rating: 4.5,
    openHours: "10 AM - 7 PM",
    contact: "9123456780",
    image: "https://source.unsplash.com/300x200/?books,store",
    verified: true,
    tags: ["books", "registers", "guides"]
  },
  {
    title: "City Library",
    name: "City Library",
    category: "library",
    location: "Nehru Nagar, Delhi",
    description: "Peaceful reading space with Wi-Fi.",
    rating: 4.7,
    openHours: "8 AM - 9 PM",
    contact: "9988776655",
    image: "https://source.unsplash.com/300x200/?library,reading",
    verified: true,
    tags: ["WiFi", "quiet", "ebooks"]
  },
  {
    title: "Tech Coaching",
    name: "Tech Coaching",
    category: "coaching",
    location: "Indira Nagar, Lucknow",
    description: "Best place to learn DSA & Web Dev.",
    rating: 4.9,
    openHours: "7 AM - 10 PM",
    contact: "9876512345",
    image: "https://source.unsplash.com/300x200/?students,classroom",
    verified: true,
    tags: ["dsa", "webdev", "java"]
  },
  {
    title: "Focus Academy",
    name: "Focus Academy",
    category: "coaching",
    location: "Sector 22, Noida",
    description: "Special coaching for Govt Exams.",
    rating: 4.4,
    openHours: "6 AM - 9 PM",
    contact: "9543217890",
    image: "https://source.unsplash.com/300x200/?classroom,learning",
    verified: true,
    tags: ["ssc", "banking", "upsc"]
  },
  {
    title: "Smart Study Point",
    name: "Smart Study Point",
    category: "coaching",
    location: "Laxmi Nagar, Delhi",
    description: "Crash courses and regular coaching.",
    rating: 4.2,
    openHours: "8 AM - 6 PM",
    contact: "9412345678",
    image: "https://source.unsplash.com/300x200/?teaching,board",
    verified: true,
    tags: ["physics", "maths", "english"]
  },
  {
    title: "Paper & Pen",
    name: "Paper & Pen",
    category: "stationery",
    location: "Alambagh, Lucknow",
    description: "Premium writing material supplier.",
    rating: 4.1,
    openHours: "10 AM - 8 PM",
    contact: "9876540000",
    image: "https://source.unsplash.com/300x200/?pen,notebook",
    verified: false,
    tags: ["gel pens", "diaries", "project files"]
  },
  {
    title: "Career Boost",
    name: "Career Boost",
    category: "coaching",
    location: "Gomti Nagar, Lucknow",
    description: "Career counselling and test prep.",
    rating: 4.6,
    openHours: "9 AM - 8 PM",
    contact: "9111122222",
    image: "https://source.unsplash.com/300x200/?career,students",
    verified: true,
    tags: ["counseling", "aptitude", "mock tests"]
  },
  {
    title: "Study Den",
    name: "Study Den",
    category: "library",
    location: "Rohini, Delhi",
    description: "24x7 library with power backup.",
    rating: 4.8,
    openHours: "24x7",
    contact: "9223344556",
    image: "https://source.unsplash.com/300x200/?study,library",
    verified: true,
    tags: ["silent zone", "coffee", "AC"]
  },
  {
    title: "Bright Minds Coaching",
    name: "Bright Minds Coaching",
    category: "coaching",
    location: "Civil Lines, Kanpur",
    description: "Focus on conceptual learning.",
    rating: 4.3,
    openHours: "7 AM - 8 PM",
    contact: "9988998899",
    image: "https://source.unsplash.com/300x200/?classroom,students",
    verified: false,
    tags: ["neet", "jee", "cbse"]
  },
  {
    title: "Book Bazaar",
    name: "Book Bazaar",
    category: "stationery",
    location: "Gandhi Road, Agra",
    description: "Affordable books and study tools.",
    rating: 4.0,
    openHours: "10 AM - 7 PM",
    contact: "9898989898",
    image: "https://source.unsplash.com/300x200/?bookshop,study",
    verified: false,
    tags: ["guides", "notes", "kits"]
  },
  {
    title: "Central Library",
    name: "Central Library",
    category: "library",
    location: "Hazratganj, Lucknow",
    description: "Ideal for research and group study.",
    rating: 4.6,
    openHours: "9 AM - 9 PM",
    contact: "9000112233",
    image: "https://source.unsplash.com/300x200/?library,books",
    verified: true,
    tags: ["research", "wifi", "group"]
  },
  {
    title: "Exam Master",
    name: "Exam Master Coaching",
    category: "coaching",
    location: "Kukrail, Lucknow",
    description: "Best test series and doubt clearing.",
    rating: 4.5,
    openHours: "7 AM - 9 PM",
    contact: "8888999900",
    image: "https://source.unsplash.com/300x200/?test,students",
    verified: true,
    tags: ["mock tests", "pdfs", "live doubt"]
  },
  {
    title: "Note Point",
    name: "Note Point",
    category: "stationery",
    location: "Sector 62, Noida",
    description: "Full stock of exam notes and files.",
    rating: 4.3,
    openHours: "10 AM - 8 PM",
    contact: "9555666777",
    image: "https://source.unsplash.com/300x200/?notes,stationery",
    verified: false,
    tags: ["exam notes", "printouts", "files"]
  },
  {
    title: "ReadMore Library",
    name: "ReadMore Library",
    category: "library",
    location: "Pitampura, Delhi",
    description: "Affordable monthly reading room.",
    rating: 4.4,
    openHours: "7 AM - 11 PM",
    contact: "8447332112",
    image: "https://source.unsplash.com/300x200/?reading,students",
    verified: true,
    tags: ["reading", "budget", "long hour"]
  },
  {
    title: "Aspire Coaching",
    name: "Aspire Coaching Centre",
    category: "coaching",
    location: "Vaishali, Ghaziabad",
    description: "Targeted preparation for SSC/Bank PO.",
    rating: 4.7,
    openHours: "6 AM - 10 PM",
    contact: "7766554433",
    image: "https://source.unsplash.com/300x200/?ssc,coaching",
    verified: true,
    tags: ["ssc", "bank po", "online"]
  },
  {
    title: "Top Rankers",
    name: "Top Rankers Classes",
    category: "coaching",
    location: "Saket, Delhi",
    description: "Weekend and daily batch options.",
    rating: 4.2,
    openHours: "7 AM - 8 PM",
    contact: "8123456789",
    image: "https://source.unsplash.com/300x200/?students,rank",
    verified: false,
    tags: ["target batch", "weekly test"]
  },
  {
    title: "Stationery Point",
    name: "Stationery Point",
    category: "stationery",
    location: "Model Town, Delhi",
    description: "Color print, Xerox, spiral binding.",
    rating: 4.0,
    openHours: "10 AM - 7 PM",
    contact: "7766551122",
    image: "https://source.unsplash.com/300x200/?print,xerox",
    verified: true,
    tags: ["print", "xerox", "binding"]
  },
  {
    title: "Library Nest",
    name: "Library Nest",
    category: "library",
    location: "DLF Phase 2, Gurugram",
    description: "Premium cubicle based library.",
    rating: 4.9,
    openHours: "6 AM - 12 AM",
    contact: "9090909090",
    image: "https://source.unsplash.com/300x200/?library,cubicle",
    verified: true,
    tags: ["cubicle", "wifi", "air purifier"]
  },
  {
    title: "Career Pathway",
    name: "Career Pathway",
    category: "coaching",
    location: "Nirala Nagar, Lucknow",
    description: "Interview & communication classes.",
    rating: 4.6,
    openHours: "8 AM - 8 PM",
    contact: "9345678901",
    image: "https://source.unsplash.com/300x200/?interview,preparation",
    verified: true,
    tags: ["HR round", "soft skills", "english"]
  },
  {
    title: "The Pen House",
    name: "The Pen House",
    category: "stationery",
    location: "Beta 1, Greater Noida",
    description: "Specialized in high-end pens.",
    rating: 4.2,
    openHours: "11 AM - 7 PM",
    contact: "9432211144",
    image: "https://source.unsplash.com/300x200/?pens,stationery",
    verified: false,
    tags: ["luxury pen", "refill", "ink"]
  },
  {
    title: "Vision Library",
    name: "Vision Library",
    category: "library",
    location: "Aashiana, Lucknow",
    description: "Cool & calm environment to study.",
    rating: 4.5,
    openHours: "7 AM - 11 PM",
    contact: "8900980098",
    image: "https://source.unsplash.com/300x200/?focus,study",
    verified: true,
    tags: ["focus zone", "clean", "fan"]
  },
  {
    title: "Study Zone",
    name: "Study Zone",
    category: "library",
    location: "Sector 12, Faridabad",
    description: "Student friendly ambience.",
    rating: 4.1,
    openHours: "6 AM - 9 PM",
    contact: "9011223344",
    image: "https://source.unsplash.com/300x200/?study,table",
    verified: false,
    tags: ["quiet", "wifi", "refreshment"]
  },
  {
    title: "Idea Institute",
    name: "Idea Institute",
    category: "coaching",
    location: "Palam, Delhi",
    description: "Full subject coaching for classes 9–12.",
    rating: 4.5,
    openHours: "9 AM - 7 PM",
    contact: "9333001122",
    image: "https://source.unsplash.com/300x200/?coaching,students",
    verified: true,
    tags: ["cbse", "science", "commerce"]
  },
  {
    title: "Study Supply",
    name: "Study Supply Store",
    category: "stationery",
    location: "Kalkaji, Delhi",
    description: "One stop for student stationery.",
    rating: 4.3,
    openHours: "10 AM - 8 PM",
    contact: "7878787878",
    image: "https://source.unsplash.com/300x200/?stationery,shop",
    verified: true,
    tags: ["projects", "paper", "art"]
  },
  {
    title: "Scholar Library",
    name: "Scholar Library",
    category: "library",
    location: "Preet Vihar, Delhi",
    description: "AC cabins and hygienic toilets.",
    rating: 4.8,
    openHours: "6 AM - 11 PM",
    contact: "8000000000",
    image: "https://source.unsplash.com/300x200/?studyroom,reading",
    verified: true,
    tags: ["cabins", "fan", "water"]
  },
  {
    title: "NCR Classes",
    name: "NCR Classes",
    category: "coaching",
    location: "Sector 3, Ghaziabad",
    description: "JEE & NEET focused coaching.",
    rating: 4.7,
    openHours: "8 AM - 9 PM",
    contact: "8111222333",
    image: "https://source.unsplash.com/300x200/?neet,jee",
    verified: true,
    tags: ["neet", "jee", "batches"]
  },
  {
    title: "EduKart Plus",
    name: "EduKart Plus Store",
    category: "stationery",
    location: "Rajouri Garden, Delhi",
    description: "Educational accessories available.",
    rating: 4.1,
    openHours: "10 AM - 6 PM",
    contact: "9333222111",
    image: "https://source.unsplash.com/300x200/?accessories,education",
    verified: true,
    tags: ["lab items", "calculator", "geometry"]
  },
  {
    title: "Zenith Library",
    name: "Zenith Library",
    category: "library",
    location: "Boring Road, Patna",
    description: "Aesthetic reading and relaxation zone.",
    rating: 4.6,
    openHours: "8 AM - 10 PM",
    contact: "8777666555",
    image: "https://source.unsplash.com/300x200/?reading,chair",
    verified: true,
    tags: ["relax", "corner seat", "books"]
  },
  {
    title: "Prime Coaching",
    name: "Prime Coaching",
    category: "coaching",
    location: "Rajendra Place, Delhi",
    description: "Mentorship-driven exam strategy.",
    rating: 4.4,
    openHours: "7 AM - 9 PM",
    contact: "9090908080",
    image: "https://source.unsplash.com/300x200/?mentor,study",
    verified: true,
    tags: ["strategy", "mentor", "routine"]
  }
];
 
module.exports = {data : sampleListings };