const sampleListings = [
 {
  title: "Elite Book House",
  name: "Elite Book House",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Karol Bagh, Delhi",
  contact: "9876543210",
  alternateContact: "9123456789",
  whatsappNumber: "9876543210",
  email: "elitebookhouse@gmail.com",
  website: "https://elitebookhouse.com",
  googleMapLink: "https://maps.google.com/elitebookhouse",
  facebookPage: "https://facebook.com/elitebookhouse",
  instagramPage: "https://instagram.com/elitebookhouse",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore1" }
},
{
  title: "Peaceful Pages Library",
  name: "Peaceful Pages Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Saket, Delhi",
  contact: "9345678901",
  alternateContact: "9567890123",
  whatsappNumber: "9345678901",
  email: "peacefulpages@gmail.com",
  website: "https://peacefulpages.com",
  googleMapLink: "https://maps.google.com/peacefulpages",
  facebookPage: "https://facebook.com/peacefulpages",
  instagramPage: "https://instagram.com/peacefulpages",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library1" }
},
{
  title: "Creative Supplies",
  name: "Creative Supplies",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Chandni Chowk, Delhi",
  contact: "9123456780",
  alternateContact: "9876501234",
  whatsappNumber: "9123456780",
  email: "creativesupplies@gmail.com",
  website: "https://creativesupplies.com",
  googleMapLink: "https://maps.google.com/creativesupplies",
  facebookPage: "https://facebook.com/creativesupplies",
  instagramPage: "https://instagram.com/creativesupplies",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery1" }
},
{
  title: "Web Zone",
  name: "Web Zone",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Malviya Nagar, Delhi",
  contact: "9876501235",
  alternateContact: "9345678902",
  whatsappNumber: "9876501235",
  email: "webzone@gmail.com",
  website: "https://webzone.com",
  googleMapLink: "https://maps.google.com/webzone",
  facebookPage: "https://facebook.com/webzone",
  instagramPage: "https://instagram.com/webzone",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber1" }
},
{
  title: "Excel Coaching",
  name: "Excel Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Mukherjee Nagar, Delhi",
  contact: "9345678903",
  alternateContact: "9123456782",
  whatsappNumber: "9345678903",
  email: "excelcoaching@gmail.com",
  website: "https://excelcoaching.com",
  googleMapLink: "https://maps.google.com/excelcoaching",
  facebookPage: "https://facebook.com/excelcoaching",
  instagramPage: "https://instagram.com/excelcoaching",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching1" }
},
// ... Repeat this pattern for remaining 30 listings ...

  {
  title: "Book Nest",
  name: "Book Nest Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Janakpuri, Delhi",
  contact: "9876543210",
  alternateContact: "9123456789",
  whatsappNumber: "9876543210",
  email: "bookneststore@gmail.com",
  website: "https://bookneststore.com",
  googleMapLink: "https://maps.google.com/bookneststore",
  facebookPage: "https://facebook.com/bookneststore",
  instagramPage: "https://instagram.com/bookneststore",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore12" }
},
{
  title: "The Knowledge Room",
  name: "Knowledge Room Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Pitampura, Delhi",
  contact: "9345678901",
  alternateContact: "9567890123",
  whatsappNumber: "9345678901",
  email: "knowledgeroom@gmail.com",
  website: "https://knowledgeroom.com",
  googleMapLink: "https://maps.google.com/knowledgeroom",
  facebookPage: "https://facebook.com/knowledgeroom",
  instagramPage: "https://instagram.com/knowledgeroom",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library45" }
},
{
  title: "Note & Write",
  name: "Note & Write Stationers",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Ashok Vihar, Delhi",
  contact: "9123456780",
  alternateContact: "9876501234",
  whatsappNumber: "9123456780",
  email: "notewrite@gmail.com",
  website: "https://notewrite.com",
  googleMapLink: "https://maps.google.com/notewrite",
  facebookPage: "https://facebook.com/notewrite",
  instagramPage: "https://instagram.com/notewrite",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery22" }
},
{
  title: "Speed Net Cafe",
  name: "Speed Net Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Kalkaji, Delhi",
  contact: "9876501235",
  alternateContact: "9345678902",
  whatsappNumber: "9876501235",
  email: "speednetcafe@gmail.com",
  website: "https://speednetcafe.com",
  googleMapLink: "https://maps.google.com/speednetcafe",
  facebookPage: "https://facebook.com/speednetcafe",
  instagramPage: "https://instagram.com/speednetcafe",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber55" }
},
{
  title: "Prime Success Tutorials",
  name: "Prime Success Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Vaishali, Ghaziabad",
  contact: "9345678903",
  alternateContact: "9123456782",
  whatsappNumber: "9345678903",
  email: "primesuccess@gmail.com",
  website: "https://primesuccess.com",
  googleMapLink: "https://maps.google.com/primesuccess",
  facebookPage: "https://facebook.com/primesuccess",
  instagramPage: "https://instagram.com/primesuccess",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching78" }
},
{
  title: "Readers' Stop",
  name: "Readers' Stop Bookstore",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Rohini, Delhi",
  contact: "9876549870",
  alternateContact: "9123487654",
  whatsappNumber: "9876549870",
  email: "readersstop@gmail.com",
  website: "https://readersstop.com",
  googleMapLink: "https://maps.google.com/readersstop",
  facebookPage: "https://facebook.com/readersstop",
  instagramPage: "https://instagram.com/readersstop",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore27" }
},
{
  title: "Brainwave Library",
  name: "Brainwave Study Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "GTB Nagar, Delhi",
  contact: "9345634123",
  alternateContact: "9567845632",
  whatsappNumber: "9345634123",
  email: "brainwavelibrary@gmail.com",
  website: "https://brainwavelibrary.com",
  googleMapLink: "https://maps.google.com/brainwavelibrary",
  facebookPage: "https://facebook.com/brainwavelibrary",
  instagramPage: "https://instagram.com/brainwavelibrary",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library32" }
},
{
  title: "Office Mart",
  name: "Office Mart Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Tilak Nagar, Delhi",
  contact: "9123487632",
  alternateContact: "9876509876",
  whatsappNumber: "9123487632",
  email: "officemart@gmail.com",
  website: "https://officemart.com",
  googleMapLink: "https://maps.google.com/officemart",
  facebookPage: "https://facebook.com/officemart",
  instagramPage: "https://instagram.com/officemart",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery76" }
},
{
  title: "Net Connect",
  name: "Net Connect Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Mayur Vihar, Delhi",
  contact: "9876512345",
  alternateContact: "9345678923",
  whatsappNumber: "9876512345",
  email: "netconnect@gmail.com",
  website: "https://netconnect.com",
  googleMapLink: "https://maps.google.com/netconnect",
  facebookPage: "https://facebook.com/netconnect",
  instagramPage: "https://instagram.com/netconnect",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber12" }
},
{
  title: "Vision Tutorials",
  name: "Vision Success Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Shahdara, Delhi",
  contact: "9345671243",
  alternateContact: "9123456787",
  whatsappNumber: "9345671243",
  email: "visionsuccess@gmail.com",
  website: "https://visionsuccess.com",
  googleMapLink: "https://maps.google.com/visionsuccess",
  facebookPage: "https://facebook.com/visionsuccess",
  instagramPage: "https://instagram.com/visionsuccess",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching98" }
},
{
  title: "Book Cart",
  name: "Book Cart Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Dwarka, Delhi",
  contact: "9876523456",
  alternateContact: "9123498765",
  whatsappNumber: "9876523456",
  email: "bookcart@gmail.com",
  website: "https://bookcart.com",
  googleMapLink: "https://maps.google.com/bookcart",
  facebookPage: "https://facebook.com/bookcart",
  instagramPage: "https://instagram.com/bookcart",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore66" }
},
{
  title: "Page Turners Library",
  name: "Page Turners Reading Hub",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Preet Vihar, Delhi",
  contact: "9345678902",
  alternateContact: "9567894321",
  whatsappNumber: "9345678902",
  email: "pageturnerslibrary@gmail.com",
  website: "https://pageturnerslibrary.com",
  googleMapLink: "https://maps.google.com/pageturnerslibrary",
  facebookPage: "https://facebook.com/pageturnerslibrary",
  instagramPage: "https://instagram.com/pageturnerslibrary",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library88" }
},
{
  title: "Write Right",
  name: "Write Right Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Vikaspuri, Delhi",
  contact: "9123498764",
  alternateContact: "9876505678",
  whatsappNumber: "9123498764",
  email: "writeright@gmail.com",
  website: "https://writeright.com",
  googleMapLink: "https://maps.google.com/writeright",
  facebookPage: "https://facebook.com/writeright",
  instagramPage: "https://instagram.com/writeright",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery44" }
},
{
  title: "iWeb Cafe",
  name: "iWeb Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Indirapuram, Ghaziabad",
  contact: "9876532109",
  alternateContact: "9345678976",
  whatsappNumber: "9876532109",
  email: "iwebcafe@gmail.com",
  website: "https://iwebcafe.com",
  googleMapLink: "https://maps.google.com/iwebcafe",
  facebookPage: "https://facebook.com/iwebcafe",
  instagramPage: "https://instagram.com/iwebcafe",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber67" }
},
{
  title: "Target Tutorials",
  name: "Target Coaching Centre",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Noida Sector 62",
  contact: "9345674532",
  alternateContact: "9123456743",
  whatsappNumber: "9345674532",
  email: "targettutorials@gmail.com",
  website: "https://targettutorials.com",
  googleMapLink: "https://maps.google.com/targettutorials",
  facebookPage: "https://facebook.com/targettutorials",
  instagramPage: "https://instagram.com/targettutorials",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching59" }
},
{
  title: "Book Junction",
  name: "Book Junction Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Karol Bagh, Delhi",
  contact: "9876501234",
  alternateContact: "9123498745",
  whatsappNumber: "9876501234",
  email: "bookjunction@gmail.com",
  website: "https://bookjunction.com",
  googleMapLink: "https://maps.google.com/bookjunction",
  facebookPage: "https://facebook.com/bookjunction",
  instagramPage: "https://instagram.com/bookjunction",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore29" }
},
{
  title: "Study Lounge",
  name: "Study Lounge Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Vasant Kunj, Delhi",
  contact: "9345612345",
  alternateContact: "9567893210",
  whatsappNumber: "9345612345",
  email: "studylounge@gmail.com",
  website: "https://studylounge.com",
  googleMapLink: "https://maps.google.com/studylounge",
  facebookPage: "https://facebook.com/studylounge",
  instagramPage: "https://instagram.com/studylounge",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library90" }
},
{
  title: "Paper Palace",
  name: "Paper Palace Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Punjabi Bagh, Delhi",
  contact: "9123487654",
  alternateContact: "9876502345",
  whatsappNumber: "9123487654",
  email: "paperpalace@gmail.com",
  website: "https://paperpalace.com",
  googleMapLink: "https://maps.google.com/paperpalace",
  facebookPage: "https://facebook.com/paperpalace",
  instagramPage: "https://instagram.com/paperpalace",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery54" }
},
{
  title: "Cyber World",
  name: "Cyber World Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Yamuna Vihar, Delhi",
  contact: "9876598765",
  alternateContact: "9345678909",
  whatsappNumber: "9876598765",
  email: "cyberworldcafe@gmail.com",
  website: "https://cyberworldcafe.com",
  googleMapLink: "https://maps.google.com/cyberworldcafe",
  facebookPage: "https://facebook.com/cyberworldcafe",
  instagramPage: "https://instagram.com/cyberworldcafe",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber81" }
},
{
  title: "Achievers Academy",
  name: "Achievers Coaching Centre",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Uttam Nagar, Delhi",
  contact: "9345670987",
  alternateContact: "9123456788",
  whatsappNumber: "9345670987",
  email: "achieversacademy@gmail.com",
  website: "https://achieversacademy.com",
  googleMapLink: "https://maps.google.com/achieversacademy",
  facebookPage: "https://facebook.com/achieversacademy",
  instagramPage: "https://instagram.com/achieversacademy",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching42" }
},
{
  title: "Page World",
  name: "Page World Bookstore",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Connaught Place, Delhi",
  contact: "9876505678",
  alternateContact: "9123456732",
  whatsappNumber: "9876505678",
  email: "pageworld@gmail.com",
  website: "https://pageworld.com",
  googleMapLink: "https://maps.google.com/pageworld",
  facebookPage: "https://facebook.com/pageworld",
  instagramPage: "https://instagram.com/pageworld",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore71" }
},
{
  title: "Smart Reads",
  name: "Smart Reads Library",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Saket, Delhi",
  contact: "9345673210",
  alternateContact: "9567898743",
  whatsappNumber: "9345673210",
  email: "smartreads@gmail.com",
  website: "https://smartreads.com",
  googleMapLink: "https://maps.google.com/smartreads",
  facebookPage: "https://facebook.com/smartreads",
  instagramPage: "https://instagram.com/smartreads",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library65" }
},
{
  title: "The Stationery Hub",
  name: "Stationery Hub",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Ashok Vihar, Delhi",
  contact: "9123456789",
  alternateContact: "9876543211",
  whatsappNumber: "9123456789",
  email: "stationeryhub@gmail.com",
  website: "https://stationeryhub.com",
  googleMapLink: "https://maps.google.com/stationeryhub",
  facebookPage: "https://facebook.com/stationeryhub",
  instagramPage: "https://instagram.com/stationeryhub",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery33" }
},
{
  title: "Fast Lane Cafe",
  name: "Fast Lane Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Kalkaji, Delhi",
  contact: "9876506789",
  alternateContact: "9345678910",
  whatsappNumber: "9876506789",
  email: "fastlanecafe@gmail.com",
  website: "https://fastlanecafe.com",
  googleMapLink: "https://maps.google.com/fastlanecafe",
  facebookPage: "https://facebook.com/fastlanecafe",
  instagramPage: "https://instagram.com/fastlanecafe",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber32" }
},
{
  title: "Champions Institute",
  name: "Champions Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Noida Sector 62",
  contact: "9345676543",
  alternateContact: "9123456781",
  whatsappNumber: "9345676543",
  email: "championsinstitute@gmail.com",
  website: "https://championsinstitute.com",
  googleMapLink: "https://maps.google.com/championsinstitute",
  facebookPage: "https://facebook.com/championsinstitute",
  instagramPage: "https://instagram.com/championsinstitute",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching73" }
},
{
  title: "The Book Shelf",
  name: "The Book Shelf Store",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Model Town, Delhi",
  contact: "9876532109",
  alternateContact: "9123450987",
  whatsappNumber: "9876532109",
  email: "thebookshelf@gmail.com",
  website: "https://thebookshelf.com",
  googleMapLink: "https://maps.google.com/thebookshelf",
  facebookPage: "https://facebook.com/thebookshelf",
  instagramPage: "https://instagram.com/thebookshelf",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore98" }
},
{
  title: "Library Hub",
  name: "Library Hub Reading Center",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "GTB Nagar, Delhi",
  contact: "9345677654",
  alternateContact: "9567891234",
  whatsappNumber: "9345677654",
  email: "libraryhub@gmail.com",
  website: "https://libraryhub.com",
  googleMapLink: "https://maps.google.com/libraryhub",
  facebookPage: "https://facebook.com/libraryhub",
  instagramPage: "https://instagram.com/libraryhub",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library77" }
},
{
  title: "Office Point",
  name: "Office Point Stationery",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Chandni Chowk, Delhi",
  contact: "9123455678",
  alternateContact: "9876501230",
  whatsappNumber: "9123455678",
  email: "officepoint@gmail.com",
  website: "https://officepoint.com",
  googleMapLink: "https://maps.google.com/officepoint",
  facebookPage: "https://facebook.com/officepoint",
  instagramPage: "https://instagram.com/officepoint",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery50" }
},
{
  title: "iConnect Cafe",
  name: "iConnect Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Indirapuram, Ghaziabad",
  contact: "9876509876",
  alternateContact: "9345678900",
  whatsappNumber: "9876509876",
  email: "iconnectcafe@gmail.com",
  website: "https://iconnectcafe.com",
  googleMapLink: "https://maps.google.com/iconnectcafe",
  facebookPage: "https://facebook.com/iconnectcafe",
  instagramPage: "https://instagram.com/iconnectcafe",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber58" }
},
{
  title: "Bright Future Tutorials",
  name: "Bright Future Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Mukherjee Nagar, Delhi",
  contact: "9345673321",
  alternateContact: "9123458888",
  whatsappNumber: "9345673321",
  email: "brightfuturetutorials@gmail.com",
  website: "https://brightfuturetutorials.com",
  googleMapLink: "https://maps.google.com/brightfuturetutorials",
  facebookPage: "https://facebook.com/brightfuturetutorials",
  instagramPage: "https://instagram.com/brightfuturetutorials",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching80" }
},
{
  title: "Book Corner",
  name: "Book Corner Bookstore",
  category: "Bookstore",
  description: "Wide range of academic, fiction & non-fiction books available.",
  location: "Paharganj, Delhi",
  contact: "9876504567",
  alternateContact: "9123450999",
  whatsappNumber: "9876504567",
  email: "bookcorner@gmail.com",
  website: "https://bookcorner.com",
  googleMapLink: "https://maps.google.com/bookcorner",
  facebookPage: "https://facebook.com/bookcorner",
  instagramPage: "https://instagram.com/bookcorner",
  image: { url: "https://source.unsplash.com/800x600/?bookstore", filename: "bookstore58" }
},
{
  title: "Peace Library",
  name: "Peace Library & Study Hub",
  category: "Library",
  description: "Peaceful environment with free Wi-Fi and a huge collection of books.",
  location: "Laxmi Nagar, Delhi",
  contact: "9345672222",
  alternateContact: "9567896543",
  whatsappNumber: "9345672222",
  email: "peacelibrary@gmail.com",
  website: "https://peacelibrary.com",
  googleMapLink: "https://maps.google.com/peacelibrary",
  facebookPage: "https://facebook.com/peacelibrary",
  instagramPage: "https://instagram.com/peacelibrary",
  image: { url: "https://source.unsplash.com/800x600/?library", filename: "library40" }
},
{
  title: "Pen & Paper",
  name: "Pen & Paper Stationers",
  category: "Stationery",
  description: "All school, college, and office supplies under one roof.",
  location: "Karawal Nagar, Delhi",
  contact: "9123454321",
  alternateContact: "9876501111",
  whatsappNumber: "9123454321",
  email: "penandpaper@gmail.com",
  website: "https://penandpaper.com",
  googleMapLink: "https://maps.google.com/penandpaper",
  facebookPage: "https://facebook.com/penandpaper",
  instagramPage: "https://instagram.com/penandpaper",
  image: { url: "https://source.unsplash.com/800x600/?stationery", filename: "stationery78" }
},
{
  title: "Click Net Cafe",
  name: "Click Net Cyber Cafe",
  category: "Cyber Cafe",
  description: "High-speed internet with photocopying & scanning services.",
  location: "Noida Sector 15",
  contact: "9876506543",
  alternateContact: "9345677654",
  whatsappNumber: "9876506543",
  email: "clicknetcafe@gmail.com",
  website: "https://clicknetcafe.com",
  googleMapLink: "https://maps.google.com/clicknetcafe",
  facebookPage: "https://facebook.com/clicknetcafe",
  instagramPage: "https://instagram.com/clicknetcafe",
  image: { url: "https://source.unsplash.com/800x600/?cybercafe", filename: "cyber70" }
},
{
  title: "Success Gurukul",
  name: "Success Gurukul Coaching",
  category: "Coaching",
  description: "Expert faculty for competitive exams with result-oriented approach.",
  location: "Patel Nagar, Delhi",
  contact: "9345675432",
  alternateContact: "9123456543",
  whatsappNumber: "9345675432",
  email: "successgurukul@gmail.com",
  website: "https://successgurukul.com",
  googleMapLink: "https://maps.google.com/successgurukul",
  facebookPage: "https://facebook.com/successgurukul",
  instagramPage: "https://instagram.com/successgurukul",
  image: { url: "https://source.unsplash.com/800x600/?coaching", filename: "coaching66" }
},
];
 
module.exports = sampleListings ;