const sampleListings = [
  {
  title: "Goyal Stationery",
    name: "Goyal Stationery",
    category: "stationery",
    location: "Sector 10, Noida",
    description: "Complete range of stationery and office supplies with affordable pricing.",
    rating: 4.5,
    openHours: "9 AM - 8 PM",
    contact: "9876543210",
    image: "https://source.unsplash.com/300x200/?stationery,store",
    verified: true,
    tags: ["notebooks", "pens", "xerox"]
  },
  {
    title: "Sharma Book Depot",
    name: "Sharma Book Depot",
    category: "stationery",
    location: "Rajpur Road, Dehradun",
    description: "All school & college books available.",
    rating: 4.4,
    openHours: "10 AM - 7 PM",
    contact: "9123456780",
    image: "https://source.unsplash.com/300x200/?books,store",
    verified: true,
    tags: ["registers", "drawing books"]
  },
  {
    title: "Smart Stationers",
    name: "Smart Stationers",
    category: "stationery",
    location: "MG Road, Pune",
    description: "Best-selling stationery items for students and offices.",
    rating: 4.2,
    openHours: "9 AM - 8 PM",
    contact: "9988776655",
    image: "https://source.unsplash.com/300x200/?pen,stationery",
    verified: true,
    tags: ["office", "school", "print"]
  },
  {
    title: "Paper Point",
    name: "Paper Point",
    category: "stationery",
    location: "Hazratganj, Lucknow",
    description: "One stop shop for all your stationery needs.",
    rating: 4.0,
    openHours: "10 AM - 7 PM",
    contact: "9090909090",
    image: "https://source.unsplash.com/300x200/?paper,shop",
    verified: true,
    tags: ["papers", "xerox"]
  },
  {
    title: "NoteHub Stationery",
    name: "NoteHub Stationery",
    category: "stationery",
    location: "Laxmi Nagar, Delhi",
    description: "Popular student choice for notes and writing materials.",
    rating: 4.6,
    openHours: "8 AM - 9 PM",
    contact: "8800880088",
    image: "https://source.unsplash.com/300x200/?stationery",
    verified: true,
    tags: ["notes", "files", "refills"]
  },

  // 5 CYBER CAFES
  {
    title: "NetZone Cafe",
    name: "NetZone Cafe",
    category: "cyber",
    location: "Sector 10, Noida",
    description: "High-speed internet with printing and scanning.",
    rating: 4.3,
    openHours: "9 AM - 8 PM",
    contact: "9876543210",
    image: "https://source.unsplash.com/300x200/?cyber,cafe",
    verified: true,
    tags: ["internet", "print", "scan"]
  },
  {
    title: "TechSpace Cafe",
    name: "TechSpace Cafe",
    category: "cyber",
    location: "MG Road, Pune",
    description: "Reliable and fast internet connection available.",
    rating: 4.2,
    openHours: "10 AM - 8 PM",
    contact: "9090909090",
    image: "https://source.unsplash.com/300x200/?computer,cyber",
    verified: true,
    tags: ["documents", "wifi"]
  },
  {
    title: "ClickNet Hub",
    name: "ClickNet Hub",
    category: "cyber",
    location: "Hazratganj, Lucknow",
    description: "Great place for urgent online work & services.",
    rating: 4.0,
    openHours: "9:30 AM - 6:30 PM",
    contact: "9123456780",
    image: "https://source.unsplash.com/300x200/?internet,cafe",
    verified: true,
    tags: ["email", "aadhar print", "resume"]
  },
  {
    title: "SpeedNet Cafe",
    name: "SpeedNet Cafe",
    category: "cyber",
    location: "Laxmi Nagar, Delhi",
    description: "Popular among students for online form filling.",
    rating: 4.1,
    openHours: "10 AM - 8 PM",
    contact: "9988776655",
    image: "https://source.unsplash.com/300x200/?broadband,pc",
    verified: true,
    tags: ["form fill", "exam print"]
  },
  {
    title: "ByteConnect",
    name: "ByteConnect",
    category: "cyber",
    location: "Rajpur Road, Dehradun",
    description: "Safe and secure digital services with printing.",
    rating: 4.5,
    openHours: "9 AM - 9 PM",
    contact: "9876543210",
    image: "https://source.unsplash.com/300x200/?cybercafe,pc",
    verified: true,
    tags: ["online", "wifi"]
  },

  // 5 LIBRARIES
  {
    title: "City Library",
    name: "City Library",
    category: "library",
    location: "Sector 10, Noida",
    description: "Peaceful environment with wide book collections.",
    rating: 4.7,
    openHours: "8 AM - 9 PM",
    contact: "9876543210",
    image: "https://source.unsplash.com/300x200/?library,reading",
    verified: true,
    tags: ["books", "wifi", "study"]
  },
  {
    title: "Readers’ Spot",
    name: "Readers’ Spot",
    category: "library",
    location: "Rajpur Road, Dehradun",
    description: "Best for focused preparation and research.",
    rating: 4.4,
    openHours: "9 AM - 8 PM",
    contact: "9123456780",
    image: "https://source.unsplash.com/300x200/?books,library",
    verified: true,
    tags: ["peaceful", "notes", "magazines"]
  },
  {
    title: "NCR Library",
    name: "NCR Library",
    category: "library",
    location: "MG Road, Pune",
    description: "All competitive books and AC facility.",
    rating: 4.3,
    openHours: "9 AM - 7 PM",
    contact: "9988776655",
    image: "https://source.unsplash.com/300x200/?study,library",
    verified: true,
    tags: ["govt exams", "free wifi"]
  },
  {
    title: "Wisdom Hall",
    name: "Wisdom Hall",
    category: "library",
    location: "Hazratganj, Lucknow",
    description: "Serene and neat library with large seating capacity.",
    rating: 4.5,
    openHours: "10 AM - 8 PM",
    contact: "9090909090",
    image: "https://source.unsplash.com/300x200/?public,library",
    verified: true,
    tags: ["air cooled", "ebooks"]
  },
  {
    title: "Urban Book Vault",
    name: "Urban Book Vault",
    category: "library",
    location: "Laxmi Nagar, Delhi",
    description: "Premium library for students and readers alike.",
    rating: 4.6,
    openHours: "8 AM - 9 PM",
    contact: "8800880088",
    image: "https://source.unsplash.com/300x200/?library",
    verified: true,
    tags: ["paid seats", "magazines"]
  },

  // 5 COACHING CENTERS (Sample)
  {
    title: "Focus Academy",
    name: "Focus Academy",
    category: "coaching",
    location: "MG Road, Pune",
    description: "Focused exam-oriented coaching with experienced faculty.",
    rating: 4.7,
    openHours: "8 AM - 7 PM",
    contact: "9876543210",
    image: "https://source.unsplash.com/300x200/?classroom,coaching",
    verified: true,
    tags: ["SSC", "Bank", "Railway"]
  },
   {
    title: "Apex Institute",
    name: "Apex Institute",
    category: "coaching",
    location: "Rajpur Road, Dehradun",
    description: "Expert coaching for IIT-JEE and NEET aspirants.",
    rating: 4.8,
    openHours: "9 AM - 7 PM",
    contact: "9999999999",
    image: "https://source.unsplash.com/300x200/?coaching,classroom",
    verified: true,
    tags: ["IIT", "NEET", "foundation"]
  },
  {
    title: "Bright Minds",
    name: "Bright Minds",
    category: "coaching",
    location: "Laxmi Nagar, Delhi",
    description: "Crash courses and regular batches for SSC and Banking.",
    rating: 4.6,
    openHours: "8 AM - 6 PM",
    contact: "9811122233",
    image: "https://source.unsplash.com/300x200/?teaching,students",
    verified: true,
    tags: ["SSC", "Bank", "UPSC"]
  },
  {
    title: "Scholars Academy",
    name: "Scholars Academy",
    category: "coaching",
    location: "MG Road, Pune",
    description: "Highly rated coaching center with personalized mentorship.",
    rating: 4.5,
    openHours: "10 AM - 8 PM",
    contact: "9823456789",
    image: "https://source.unsplash.com/300x200/?study,classroom",
    verified: true,
    tags: ["mentorship", "exams"]
  },
  {
    title: "Elite Tutorials",
    name: "Elite Tutorials",
    category: "coaching",
    location: "Hazratganj, Lucknow",
    description: "Result-oriented institute for competitive and school exams.",
    rating: 4.4,
    openHours: "9 AM - 7 PM",
    contact: "9988776655",
    image: "https://source.unsplash.com/300x200/?students,tutor",
    verified: true,
    tags: ["10th", "12th", "CUET"]
  },

  // --- 14 Bookstores
  {
    title: "Book Bazaar",
    name: "Book Bazaar",
    category: "bookstore",
    location: "Sector 18, Noida",
    description: "Largest collection of academic and fiction books.",
    rating: 4.6,
    openHours: "10 AM - 9 PM",
    contact: "9876543210",
    image: "init/images/bookshop.png",
    verified: true,
    tags: ["academic", "novels"]
  },
  {
    title: "ReadMore Library",
    name: "ReadMore Library",
    category: "bookstore",
    location: "MG Road, Pune",
    description: "Amazing discounts on bestsellers and competitive books.",
    rating: 4.5,
    openHours: "9 AM - 8 PM",
    contact: "9123456780",
    image: "init/images/bookshop.png",
    verified: true,
    tags: ["discount", "guide"]
  },
  {
    title: "The Pen House",
    name: "The Pen House",
    category: "bookstore",
    location: "Rajpur Road, Dehradun",
    description: "All types of books and writing instruments available.",
    rating: 4.3,
    openHours: "10 AM - 8 PM",
    contact: "9811122233",
    image: "init/images/bookshop.png",
    verified: true,
    tags: ["writing", "stationery"]
  },
  {
    title: "Knowledge Nest",
    name: "Knowledge Nest",
    category: "bookstore",
    location: "Hazratganj, Lucknow",
    description: "A cozy corner for book lovers and learners.",
    rating: 4.7,
    openHours: "10 AM - 9 PM",
    contact: "9090909090",
    image: "init/images/bookshop.png",
    verified: true,
    tags: ["cozy", "reading"]
  },
  {
    title: "Prime Books",
    name: "Prime Books",
    category: "bookstore",
    location: "Laxmi Nagar, Delhi",
    description: "Popular bookshop with school & college curriculum books.",
    rating: 4.5,
    openHours: "9 AM - 8 PM",
    contact: "9988776655",
    image: "init/images/bookshop.png",
    verified: true,
    tags: ["school", "college"]
  },
  // 🟣 Remaining Bookstore Listings (9)

{
  title: "The Book Nook",
  name: "The Book Nook",
  category: "bookstore",
  location: "Hazratganj, Lucknow",
  description: "Charming bookstore offering fiction, non-fiction, and rare editions.",
  rating: 4.8,
  openHours: "10 AM - 9 PM",
  contact: "9067891234",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["fiction", "non-fiction", "bestsellers"]
},
{
  title: "Chapter One Bookstore",
  name: "Chapter One",
  category: "bookstore",
  location: "Sector 62, Noida",
  description: "Modern bookstore with a cafe and relaxed reading spaces.",
  rating: 4.6,
  openHours: "10 AM - 9 PM",
  contact: "9875612340",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["cafe", "reading", "students"]
},
{
  title: "Books & Beans",
  name: "Books & Beans",
  category: "bookstore",
  location: "Jubilee Hills, Hyderabad",
  description: "Popular spot for students and coffee lovers alike.",
  rating: 4.7,
  openHours: "9 AM - 10 PM",
  contact: "9765412398",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["novels", "stationery", "coffee"]
},
{
  title: "The Reading Room",
  name: "The Reading Room",
  category: "bookstore",
  location: "Park Street, Kolkata",
  description: "Vintage bookshop with classic literature and poetry sections.",
  rating: 4.4,
  openHours: "10 AM - 8 PM",
  contact: "9867543120",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["poetry", "literature", "authors"]
},
{
  title: "Knowledge Point",
  name: "Knowledge Point",
  category: "bookstore",
  location: "Sector 20, Chandigarh",
  description: "All academic books from school to competitive exams under one roof.",
  rating: 4.6,
  openHours: "9 AM - 9 PM",
  contact: "9978632145",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["academic", "CBSE", "competitive"]
},
{
  title: "Infinity Books",
  name: "Infinity Books",
  category: "bookstore",
  location: "Camp, Pune",
  description: "A wide collection of international authors and niche genres.",
  rating: 4.5,
  openHours: "11 AM - 9 PM",
  contact: "9045312678",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["foreign authors", "graphic novels", "bestsellers"]
},
{
  title: "The Scholar's Stop",
  name: "The Scholar's Stop",
  category: "bookstore",
  location: "Sector 11, Ghaziabad",
  description: "One-stop shop for all educational books and materials.",
  rating: 4.3,
  openHours: "9 AM - 8 PM",
  contact: "9945612032",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["textbooks", "reference", "stationery"]
},
{
  title: "Pages & Chapters",
  name: "Pages & Chapters",
  category: "bookstore",
  location: "Connaught Place, Delhi",
  description: "Curated collection of novels, self-help, and biographies.",
  rating: 4.7,
  openHours: "10 AM - 9 PM",
  contact: "9002134567",
  image: "C:\\Users\\gargv\\OneDrive\\Pictures\\myphoto\\IMG_20250510_161001634_HDR~2.jpg",
  verified: true,
  tags: ["novels", "self-help", "biography"]
},
{
  title: "Book Square",
  name: "Book Square",
  category: "bookstore",
  location: "Banjara Hills, Hyderabad",
  description: "Trendy bookstore with modern authors and cozy ambiance.",
  rating: 4.6,
  openHours: "11 AM - 10 PM",
  contact: "9845623145",
  image: "init/images/bookshop.png",
  verified: true,
  tags: ["modern", "new arrivals", "book launch"]
}

];
 
module.exports = sampleListings ;